services:
  server:
    container_name: mountaintea-makemigrations
    env_file: ".env"
    build:
      context: .
      target: makemigrations
    volumes:
      - ./:/app
    networks:
      - localnet
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mountaintea-db
    env_file: ".env"
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "dummy", "-d", "mountaintea-db" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - localnet
    hostname: db

volumes:
  db-data:
    name: "mountaintea-db-data"

networks:
  localnet:
    driver: bridge
