services:
  server:
    container_name: mountaintea-server
    env_file: ".env"
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    volumes:
      - media-data:/app/mountaintea_band_site/media
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    networks:
      - localnet
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mountaintea-db
    image: postgres
    env_file: ".env"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "dummy", "-d", "mountaintea-db" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - localnet
    hostname: db

volumes:
  db-data:
    name: "mountaintea-db-data"
  media-data:
    name: "mountaintea-media-data"

networks:
  localnet:
    driver: bridge
